[package]
name = "mina-mesh"
version = "0.1.0"
authors = ["Mina Foundation"]
build = "build.rs"
edition = "2021"
license = "Apache-2.0"
description = "A Rust Server Implementation of the Mesh Spec for Mina"

[build-dependencies]
cynic-codegen = "3.7.3"
cynic-querygen = "3.7.3"
walkdir = "2.5.0"

[[bin]]
name = "mina-mesh"
path = "main.rs"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
cynic = { version = "3.7.3", features = ["http-surf"] }
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.121" }
surf = "2.3.2"
tokio = { version = "1.39.2", features = ["full"] }

[dependencies.mesh]
path = "./mesh-generated"
