[package]
name = "mina-mesh-cli"
version.workspace = true
authors = ["Mina Foundation"]
build = "build.rs"
edition = "2021"
license = "Apache-2.0"
description = "A Rust Server Implementation of the Mesh Spec for Mina"

[workspace.package]
version = "0.1.0"

[[bin]]
name = "mina-mesh"
path = "main.rs"

[build-dependencies]
cynic-codegen = "3.7.3"
cynic-querygen = "3.7.3"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
cynic = { version = "3.7.3", features = ["http-reqwest-blocking"] }
envy = "0.4.2"
tokio = { version = "1.39.2", features = ["full", "test-util"] }
