edition = "2021"
version = "Two"
max_width = 120
newline_style = "Unix"
tab_spaces = 2
use_small_heuristics = "Max"
imports_granularity = "Crate"
use_field_init_shorthand = true
use_try_shorthand = true
spaces_around_ranges = true
overflow_delimited_expr = true
wrap_comments = true
