edition = "2021"
ignore = ["mesh-generated"]
imports_granularity = "One"
max_width = 100
newline_style = "Unix"
overflow_delimited_expr = true
spaces_around_ranges = true
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
