/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// AccountBalanceRequest : An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountBalanceRequest {
  #[serde(rename = "network_identifier")]
  pub network_identifier: Box<models::NetworkIdentifier>,
  #[serde(rename = "account_identifier")]
  pub account_identifier: Box<models::AccountIdentifier>,
  #[serde(rename = "block_identifier", skip_serializing_if = "Option::is_none")]
  pub block_identifier: Option<Box<models::PartialBlockIdentifier>>,
  /// In some cases, the caller may not want to retrieve all available balances for an AccountIdentifier. If the currencies field is populated, only balances for the specified currencies will be returned. If not populated, all available balances will be returned.
  #[serde(rename = "currencies", skip_serializing_if = "Option::is_none")]
  pub currencies: Option<Vec<models::Currency>>,
}

impl AccountBalanceRequest {
  /// An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
  pub fn new(
    network_identifier: models::NetworkIdentifier,
    account_identifier: models::AccountIdentifier,
  ) -> AccountBalanceRequest {
    AccountBalanceRequest {
      network_identifier: Box::new(network_identifier),
      account_identifier: Box::new(account_identifier),
      block_identifier: None,
      currencies: None,
    }
  }
}
