/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// BlockRequest : A BlockRequest is utilized to make a block request on the /block endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockRequest {
  #[serde(rename = "network_identifier")]
  pub network_identifier: Box<models::NetworkIdentifier>,
  #[serde(rename = "block_identifier")]
  pub block_identifier: Box<models::PartialBlockIdentifier>,
}

impl BlockRequest {
  /// A BlockRequest is utilized to make a block request on the /block endpoint.
  pub fn new(
    network_identifier: models::NetworkIdentifier,
    block_identifier: models::PartialBlockIdentifier,
  ) -> BlockRequest {
    BlockRequest {
      network_identifier: Box::new(network_identifier),
      block_identifier: Box::new(block_identifier),
    }
  }
}
