/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// ConstructionPayloadsRequest : ConstructionPayloadsRequest is the request to `/construction/payloads`. It contains the network, a slice of operations, and arbitrary metadata that was returned by the call to `/construction/metadata`.  Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConstructionPayloadsRequest {
  #[serde(rename = "network_identifier")]
  pub network_identifier: Box<models::NetworkIdentifier>,
  #[serde(rename = "operations")]
  pub operations: Vec<models::Operation>,
  #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
  pub metadata: Option<serde_json::Value>,
  #[serde(rename = "public_keys", skip_serializing_if = "Option::is_none")]
  pub public_keys: Option<Vec<models::PublicKey>>,
}

impl ConstructionPayloadsRequest {
  /// ConstructionPayloadsRequest is the request to `/construction/payloads`. It contains the network, a slice of operations, and arbitrary metadata that was returned by the call to `/construction/metadata`.  Optionally, the request can also include an array of PublicKeys associated with the AccountIdentifiers returned in ConstructionPreprocessResponse.
  pub fn new(
    network_identifier: models::NetworkIdentifier,
    operations: Vec<models::Operation>,
  ) -> ConstructionPayloadsRequest {
    ConstructionPayloadsRequest {
      network_identifier: Box::new(network_identifier),
      operations,
      metadata: None,
      public_keys: None,
    }
  }
}
