/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// ConstructionPayloadsResponse : ConstructionTransactionResponse is returned by `/construction/payloads`. It contains an unsigned transaction blob (that is usually needed to construct the a network transaction from a collection of signatures) and an array of payloads that must be signed by the caller.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConstructionPayloadsResponse {
  #[serde(rename = "unsigned_transaction")]
  pub unsigned_transaction: String,
  #[serde(rename = "payloads")]
  pub payloads: Vec<models::SigningPayload>,
}

impl ConstructionPayloadsResponse {
  /// ConstructionTransactionResponse is returned by `/construction/payloads`. It contains an unsigned transaction blob (that is usually needed to construct the a network transaction from a collection of signatures) and an array of payloads that must be signed by the caller.
  pub fn new(unsigned_transaction: String, payloads: Vec<models::SigningPayload>) -> ConstructionPayloadsResponse {
    ConstructionPayloadsResponse {
      unsigned_transaction,
      payloads,
    }
  }
}
