/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// ConstructionCombineRequest : ConstructionCombineRequest is the input to the `/construction/combine` endpoint. It contains the unsigned transaction blob returned by `/construction/payloads` and all required signatures to create a network transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConstructionCombineRequest {
  #[serde(rename = "network_identifier")]
  pub network_identifier: Box<models::NetworkIdentifier>,
  #[serde(rename = "unsigned_transaction")]
  pub unsigned_transaction: String,
  #[serde(rename = "signatures")]
  pub signatures: Vec<models::Signature>,
}

impl ConstructionCombineRequest {
  /// ConstructionCombineRequest is the input to the `/construction/combine` endpoint. It contains the unsigned transaction blob returned by `/construction/payloads` and all required signatures to create a network transaction.
  pub fn new(
    network_identifier: models::NetworkIdentifier,
    unsigned_transaction: String,
    signatures: Vec<models::Signature>,
  ) -> ConstructionCombineRequest {
    ConstructionCombineRequest {
      network_identifier: Box::new(network_identifier),
      unsigned_transaction,
      signatures,
    }
  }
}
