/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere. 
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConstructionSubmitRequest : The transaction submission request includes a signed transaction. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConstructionSubmitRequest {
    #[serde(rename = "network_identifier")]
    pub network_identifier: Box<models::NetworkIdentifier>,
    #[serde(rename = "signed_transaction")]
    pub signed_transaction: String,
}

impl ConstructionSubmitRequest {
    /// The transaction submission request includes a signed transaction. 
    pub fn new(network_identifier: models::NetworkIdentifier, signed_transaction: String) -> ConstructionSubmitRequest {
        ConstructionSubmitRequest {
            network_identifier: Box::new(network_identifier),
            signed_transaction,
        }
    }
}

