/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere. 
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NetworkListResponse : A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkListResponse {
    #[serde(rename = "network_identifiers")]
    pub network_identifiers: Vec<models::NetworkIdentifier>,
}

impl NetworkListResponse {
    /// A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for. 
    pub fn new(network_identifiers: Vec<models::NetworkIdentifier>) -> NetworkListResponse {
        NetworkListResponse {
            network_identifiers,
        }
    }
}

