/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere. 
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transaction : Transactions contain an array of Operations that are attributable to the same TransactionIdentifier. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction {
    #[serde(rename = "transaction_identifier")]
    pub transaction_identifier: Box<models::TransactionIdentifier>,
    #[serde(rename = "operations")]
    pub operations: Vec<models::Operation>,
    #[serde(rename = "related_transactions", skip_serializing_if = "Option::is_none")]
    pub related_transactions: Option<Vec<models::RelatedTransaction>>,
    /// Transactions that are related to other transactions (like a cross-shard transaction) should include the tranaction_identifier of these transactions in the metadata. 
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl Transaction {
    /// Transactions contain an array of Operations that are attributable to the same TransactionIdentifier. 
    pub fn new(transaction_identifier: models::TransactionIdentifier, operations: Vec<models::Operation>) -> Transaction {
        Transaction {
            transaction_identifier: Box::new(transaction_identifier),
            operations,
            related_transactions: None,
            metadata: None,
        }
    }
}

